[web]
web1 ansible_host=20.127.31.158
web2 ansible_host=20.124.241.146

[app]
app1 ansible_host=40.76.235.145

[db]
db1 ansible_host=20.124.184.53

[all:vars]
ansible_user=azureuser
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
