---
galaxy_info:
  author: Michael Okanlawon
  description: Baseline packages and SSH hardening for EpicBook servers
  company: Personal Project
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - system
    - security
    - packages

dependencies: []
